# Generated by Django 3.2.17 on 2023-03-01 17:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('basic_img', imagekit.models.fields.ProcessedImageField(upload_to='profile-pictures')),
            ],
        ),
        migrations.CreateModel(
            name='CmsFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CmsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('basic_img', imagekit.models.fields.ProcessedImageField(upload_to='profile-pictures')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_home_1', models.CharField(max_length=200)),
                ('section_info_1_title', models.CharField(max_length=200)),
                ('section_info_1_description', models.TextField()),
                ('section_info_2_title', models.CharField(max_length=200)),
                ('section_info_2_description', models.TextField()),
                ('section_info_3_title', models.CharField(max_length=200)),
                ('section_info_3_description', models.TextField()),
                ('section_info_4_title', models.CharField(max_length=200)),
                ('section_info_4_description', models.TextField()),
                ('section_counter_1', models.TextField()),
                ('section_counter_1_title', models.CharField(max_length=200)),
                ('section_counter_1_description', models.TextField()),
                ('section_counter_2_title', models.CharField(max_length=200)),
                ('section_counter_2_description', models.TextField()),
                ('section_counter_3_title', models.CharField(max_length=200)),
                ('section_counter_3_description', models.TextField()),
                ('section_counter_4_title', models.CharField(max_length=200)),
                ('section_counter_4_description', models.TextField()),
                ('section_team_6_title', models.CharField(max_length=200)),
                ('section_team_6_description', models.TextField()),
                ('section_review_7_title', models.CharField(max_length=200)),
                ('section_faq_8_title', models.CharField(max_length=200)),
                ('section_faq_8_description', models.TextField()),
                ('section_up_footer_9_title', models.TextField()),
                ('section_faq_8_all', models.ManyToManyField(to='overview_app.CmsFaq')),
                ('section_options_5_many', models.ManyToManyField(to='overview_app.CmsBenefit')),
                ('section_review_7_all', models.ManyToManyField(to='overview_app.CmsReviews')),
            ],
        ),
    ]
