# Generated by Django 3.2.17 on 2023-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_1',
            field=models.TextField(default='Improve your skills and gain knowledge in one application. Become the best version of yourself'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_1_description',
            field=models.TextField(default='Downloads per day'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_1_title',
            field=models.CharField(default='1,000+', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_2_description',
            field=models.TextField(default='Users per month'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_2_title',
            field=models.CharField(default='1 Million', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_3_description',
            field=models.TextField(default='Courses'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_3_title',
            field=models.CharField(default='300+', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_4_description',
            field=models.TextField(default='Countries'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_counter_4_title',
            field=models.CharField(default='134', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_faq_8_description',
            field=models.TextField(default='Et felis vitae ac venenatis lacus cras etiam risus scelerisque auctor adipiscing in a porta'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_faq_8_title',
            field=models.CharField(default='Any questions? Check out the FAQ', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_home_1',
            field=models.CharField(default='The Best Aplication For Personal Trainers', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_1_description',
            field=models.TextField(default='Fusce lectus neque viverra risus lobortis adipiscing integer pulvinar elementum. Lorem viverra tincidunt tortor pellentesque.'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_1_title',
            field=models.CharField(default='Access on all devices', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_2_description',
            field=models.TextField(default='Vulputate convallis odio donec massa facilisis sed nibh rhoncus, maecenas. Maecenas morbi est neque pellentesque.'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_2_title',
            field=models.CharField(default='Large online library', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_3_description',
            field=models.TextField(default='Fermentum convallis mi posuere rutrum turpis duis facilisis integer. Rhoncus in in sit tellus velit quis laoreet morbi orci sed.'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_3_title',
            field=models.CharField(default='Study convenient', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_4_description',
            field=models.TextField(default='Arcu nisl aliquet vel pellentesque. Vitae nibh leo, facilisis laoreet metus, felis. Egestas id enim turpis tellus, nulla adipiscing.'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_info_4_title',
            field=models.CharField(default='Tracking results', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_review_7_title',
            field=models.CharField(default='Testimonials from students who recommend Around', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_team_6_description',
            field=models.TextField(default='Amet minim mollit deserunt ullamco\nVelit officia consequat duis enim\nExercitation veniam minim'),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_team_6_title',
            field=models.CharField(default='Online learning has already been chosen by 5 million people', max_length=200),
        ),
        migrations.AlterField(
            model_name='simplecms',
            name='section_up_footer_9_title',
            field=models.TextField(default='Ready to Get Started?'),
        ),
    ]
